POS_ERSATZBANK = "Ersatz";
POS_NA = "Nicht im Kader";
POSITIONS = ['TW','IV', 'LA', 'RA', 'ZDM', 'ZM', 'ZOM', 'LM', 'RM', 'ST'];

EVENT_TYPE_TEXT = 'TEXT';
EVENT_TYPE_WECHSEL = 'WECHSEL';
EVENT_TYPES = ['TOR', 'EIGENTOR', 'ELFMETER', 'GELB', 'GELBROT', 'ROT', EVENT_TYPE_WECHSEL];