POS_ERSATZBANK = "Ersatz";
POS_NA = "Nicht im Kader";
POSITIONS = ['TW','IV', 'LV', 'RV', 'ZDM', 'ZM', 'ZOM', 'LM', 'RM', 'ST'];

EVENT_TYPE_TEXT = 'TEXT';
EVENT_TYPE_COMMENT = "KOMMENTAR";

EVENT_TYPE_GOAL = 'TOR';
EVENT_TYPE_OWN_GOAL = 'EIGENTOR';
EVENT_TYPE_PENALTY_GOAL = 'ELFMETERTOR'
EVENT_TYPE_PENALTY = 'ELFMETER';
EVENT_TYPE_YELLOW_CARD = 'GELB';
EVENT_TYPE_YELLOW_RED_CARD = 'GELBROT';
EVENT_TYPE_RED_CARD = 'ROT';
EVENT_TYPE_SUBSTITUTION = 'WECHSEL';
EVENT_TYPES = [EVENT_TYPE_GOAL, EVENT_TYPE_OWN_GOAL, EVENT_TYPE_YELLOW_CARD, EVENT_TYPE_YELLOW_RED_CARD, EVENT_TYPE_RED_CARD];
ALL_EVENT_TYPES = EVENT_TYPES.concat(EVENT_TYPE_SUBSTITUTION, EVENT_TYPE_PENALTY_GOAL, EVENT_TYPE_PENALTY, EVENT_TYPE_TEXT, EVENT_TYPE_COMMENT);

KICKER_ID_DUMMY = "NULL";

TEAM_CODE_STURM_GRAZ = "STU";